### ISSUE TITLE
Bionic Reading® Legal Stuff

### ISSUE THREAD

**Issue by jomamaaye** [Jwuthri/BionicReading#3]
This isn't a bug, but I just want to inform y'all that the wonderful® folks at Bionic Reading® have decided to crack down on any open source projects that involves Bionic Reading®. It is advised to remove all mentioning of Bionic Reading® for now to avoid legal repercussions.

Context
<img width="746" alt="legal notice" src="https://user-images.githubusercontent.com/106170863/171383769-05f5263f-ced9-4af3-a88f-899df11e381d.png">

**Comment by Jwuthri** [comment]
Ok thank you for the information @jomamaaye  -:)
I did renamed the repository and tried to remove everything related to "bionic Reading"
